import re
import os
import unicodedata

# Define Unit 12 sentences
unit12_sentences = [
    # Tip 1 (Lesson 30)
    "the forests remaining in these areas",
    "a point moving along a straight line",
    "an organism living in the soil",
    "a tree growing in sandy soil",
    "a line beginning at this point",
    "micro-organisms living in the cell",
    "costs increasing because of scarcity of raw materials",
    "movement continuing in waves",
    "results differing from previous experiments",
    "gas escaping from the pipes",
    "problems existing in the cotton industry",
    "a sphere revolving at the base of the column",
    "personnel working in modern factories",
    "a mixture resulting from three elements",
    "plants living in a smoky atmosphere",
    "a disease beginning with high fever",
    "opinions disagreeing with the majority",
    "a disease developing from vitamin deficiency",
    "a diet lacking in protein",
    "waves moving in the same direction",
    "legislation existing for the individual",
    "a characteristic distinguishing from other species of insect",
    "factors contributing to the general situation",
    "a mixture consisting of sand, cement and water",
    "a compound consisting of salt and acids",
    "The factors emerging from the study",
    "The authors publishing in academic journals",
    "The companies competing in this sector",
    "The dynamic variables changing during the process",
    "The separate groups participating in the initial project",
    "The structural components remaining on the site",
    "The fundamental principles underlying this economic theory",
    "The independent researchers working within the administration",
    "The consistent layers forming at the bottom of the container",
    "The legal authorities acting under constitutional clauses",

    # Tip 2 (Lesson 31)
    "a diagram showing the classification",
    "a statement containing the facts",
    "an article describing the situation",
    "a wire connecting the electrodes",
    "a cover protecting the contents",
    "principles determining the right",
    "a statement defining the principles",
    "a law protecting the individual",
    "laws protecting the rights",
    "evidence proving the guilt",
    "experiments proving the theory",
    "a community cultivating the land",
    "a principle establishing the rights",
    "a gas giving off a smell",
    "a flask containing a liquid",
    "a tenant occupying premises",
    "a contract binding both parties",
    "a guarantee promising protection",
    "a policy creating many problems",
    "characteristics distinguishing this species",
    "water containing pollen dust",
    "a statement containing a description of the accident",
    "a diagram showing the classification of the species",
    "a statement addressing the whole community",
    "a report approving the decisions of the council",
    "a wire connecting the electrodes to the battery",
    "action creating confusion in the court of law",
    "an experiment demonstrating the principles of relativity",
    "an article describing the newly-discovered objects",
    "a principle determining the rights of the people",
    "a constitution establishing the rights of the people",
    "a law limiting the sale of drugs",
    "a statement defining the principles of democracy",
    "a statement containing the facts of the case",
    "an exhibition containing some of the best work",
    "evidence proving the guilt of the defendant",
    "laws protecting the freedom of the individual",
    "a promise guaranteeing the rights of the individual",
    "an innovation introducing many new methods",
    "an experiment necessitating careful observation",
    "new laws affecting every individual of community",
    "a policy granting new benefits to the old and unemployed",
    "a characteristic distinguishing this species of insect",
    "activity endangering the lives of members of the community",
    "factors governing the rate of growth",
    "a document authorizing the owner of the premises",
    "The movement of molecules could be seen in water containing pollen dust.",
    "He gave the police a statement containing a description of the accident.",
    "On this page there is a diagram showing the classification of the species.",
    "The report contains a statement addressing the whole community.",
    "A report approving the decisions of the council was read to the court.",
    "The current passes along a wire connecting the electrode to the battery.",
    "He was accused of action creating confusion in the court of law.",
    "This is an experiment demonstrating the principles of relativity.",
    "He has published an article describing the newly-discovered objects.",
    "The principle determining the rights of the people was explained in the lecture.",
    "There was no constitution establishing the rights of the people.",
    "A law limiting the sale of drugs was passed in 1936.",
    "He published a statement defining the principles of democracy.",
    "He published a statement containing the facts of the case.",
    "Last year there was an exhibition containing some of the best work of the Renaissance in Italy.",
    "The witness could provide no evidence proving the guilt of the defendant.",
    "There are many many laws protecting the freedom of the individual.",
    "This was contained in a promise guaranteeing the rights of the individual.",
    "Electrical power was an innovation introducing many new methods in industry.",
    "This could be proved in an experiment necessitating careful observation.",
    "The government has passed many new laws affecting every individual of the community.",
    "The government has proposed a policy granting new benefits to the old and unemployed.",
    "The shape of the head and thorax is a characteristic distinguishing this species of insect.",
    "They were engaged in activity endangering the lives of members of the community.",
    "There are many factors governing the rate of growth of a plant or tree.",
    "There was no signature on the document authorizing the owner of the premises to empty the rooms.",

    # Tip 3 (Lesson 32)
    "nations united in their desire for peace",
    "facts well-known to scientists",
    "a compound composed of two elements",
    "a picture simplified for children",
    "all the materials needed for their industries",
    "lead exposed to the air",
    "organisms classified in the vegetable kingdom",
    "the energy produced by an atomic pile",
    "energy produced by an atom",
    "gamma rays emitted by a small piece of cobalt",
    "woods inhabited by wild animals",
    "food produced by their enzyme action",
    "land exposed to the danger of floods",
    "information needed to develop the programme",
    "subject matter used as a basis for teaching",
    "waves emitted by the stars",
    "signals sent by artificial satellites and rockets",
    "towns surrounded by strong walls",
    "vibrations generated by the light source",
    "effects expected from the programmes",
    "programmes outlined in the reports",
    "surveys made before the 1936 Flood Control Act",
    "There were representatives from many nations united in their desire for peace.",
    "These are facts well-known to scientists.",
    "This produces a compound composed of two elements.",
    "This book contains pictures simplified for children to understand.",
    "European countries do not produce all the materials needed for their industries.",
    "A piece of lead exposed to the air becomes covered with a black film.",
    "Bacteria are microscopic organisms classified in the vegetable kingdom.",
    "The energy produced by an atomic pile is not cheap.",
    "Energy produced by an atom costs more than energy produced by coal or petroleum.",
    "The gamma rays emitted by a small piece of cobalt contained in a protecting cover penetrate to the cells.",
    "These were woods inhabited by wild animals.",
    "The fungi absorbs the liquid food produced by their enzyme action.",
    "We could see large areas of land exposed to the danger of floods.",
    "The department provides the information needed to develop the programme.",
    "The subject matter used as a basis for teaching is provided by the educational department.",
    "Electro-magnetic waves emitted by stars are recorded by radio telescope.",
    "Radio telescopes also receive radio signals sent by artificial satellites.",
    "Primitive villages gradually developed into towns surrounded by strong walls.",
    "Light consists of vibrations generated by the light source.",
    "The beneficial effects expected from the programmes outlined in the reports were described in the surveys made before the 1936 Flood Control Act."
]

# Extract all words from sentences
unique_words = set()
for sent in unit12_sentences:
    # clean punctuation, digits, split
    cleaned = re.sub(r'[^\w\s-]', ' ', sent)
    for word in cleaned.split():
        word = word.strip().lower()
        if word and not word.isdigit():
            unique_words.add(word)

# Load app.js wordDictionary
with open("app.js", "r", encoding="utf-8") as f:
    app_content = f.read()

dict_match = re.search(r'const wordDictionary = \{(.*?)\};', app_content, re.DOTALL)
dict_keys = set()
if dict_match:
    dict_content = dict_match.group(1)
    dict_keys = set(re.findall(r'["\']([^"\']+)["\']\s*:', dict_content))

# Find missing words
missing = sorted(list(unique_words - dict_keys))
print(f"Total unique words in new sentences: {len(unique_words)}")
print(f"Total keys in wordDictionary: {len(dict_keys)}")
print(f"Missing words ({len(missing)}):")

# Simple mapping logic for draft translations of missing words
common_tr = {
    "forests": "ormanlar",
    "forest": "orman",
    "point": "nokta",
    "along": "boyunca",
    "straight": "düz / doğru",
    "line": "çizgi / hat",
    "organism": "organizma",
    "soil": "toprak",
    "tree": "ağaç",
    "sandy": "kumlu",
    "beginning": "başlayan",
    "micro-organisms": "mikroorganizmalar",
    "cell": "hücre",
    "costs": "maliyetler",
    "increasing": "artan",
    "scarcity": "kıtlık",
    "raw": "ham / işlenmemiş",
    "materials": "malzemeler",
    "movement": "hareket",
    "continuing": "devam eden",
    "waves": "dalgalar",
    "results": "sonuçlar",
    "differing": "farklılık gösteren",
    "previous": "önceki",
    "gas": "gaz",
    "escaping": "sızan / kaçan",
    "pipes": "borular",
    "problems": "problemler / sorunlar",
    "existing": "var olan",
    "cotton": "pamuk",
    "industry": "endüstri / sanayi",
    "sphere": "küre",
    "revolving": "dönen / devreden",
    "base": "taban / üs",
    "column": "sütun / kolon",
    "personnel": "personel",
    "working": "çalışan",
    "mixture": "karışım",
    "resulting": "oluşan / ortaya çıkan",
    "three": "üç",
    "elements": "elementler / öğeler",
    "plants": "bitkiler",
    "smoky": "dumanlı",
    "atmosphere": "atmosfer",
    "disease": "hastalık",
    "fever": "ateş",
    "opinions": "fikirler / görüşler",
    "disagreeing": "katılmayan / uyuşmayan",
    "majority": "çoğunluk",
    "developing": "gelişen",
    "deficiency": "eksiklik",
    "diet": "diyet",
    "lacking": "eksik / yoksun",
    "protein": "protein",
    "moving": "hareket eden",
    "same": "aynı",
    "direction": "yön",
    "legislation": "mevzuat / kanunlar",
    "characteristic": "özellik / karakteristik",
    "distinguishing": "ayıran / ayırt edici",
    "species": "tür / türler",
    "insect": "böcek",
    "factors": "faktörler",
    "contributing": "katkıda bulunan",
    "general": "genel",
    "situation": "durum",
    "consisting": "oluşan",
    "sand": "kum",
    "cement": "çimento",
    "water": "su",
    "compound": "bileşik",
    "salt": "tuz",
    "acids": "asitler",
    "diagram": "şema / grafik",
    "showing": "gösteren",
    "classification": "sınıflandırma",
    "statement": "ifade / açıklama",
    "containing": "içeren",
    "facts": "gerçekler",
    "article": "makale",
    "describing": "tanımlayan / açıklayan",
    "wire": "tel / kablo",
    "connecting": "bağlayan",
    "electrodes": "elektrotlar",
    "cover": "kapak / örtü",
    "protecting": "koruyan",
    "contents": "içerik / içindekiler",
    "principles": "ilkeler / prensipler",
    "determining": "belirleyen",
    "right": "hak / doğru",
    "defining": "tanımlayan",
    "law": "yasa / kanun",
    "laws": "yasalar / kanunlar",
    "evidence": "delil / kanıt",
    "proving": "kanıtlayan / ispatlayan",
    "guilt": "suçluluk",
    "experiments": "deneyler",
    "community": "toplum / topluluk",
    "cultivating": "işleyen / ekip biçen",
    "land": "kara / toprak / arazi",
    "establishing": "kuran / tesis eden",
    "giving": "veren / yayan",
    "smell": "koku",
    "flask": "şişe / balon",
    "liquid": "sıvı",
    "tenant": "kiracı",
    "occupying": "işgal eden / oturan",
    "premises": "mülk / bina",
    "binding": "bağlayıcı",
    "both": "her iki / hem",
    "parties": "taraflar",
    "promising": "vaat eden / söz veren",
    "protection": "koruma",
    "creating": "yaratan / oluşturan",
    "characteristics": "özellikler",
    "pollen": "polen",
    "dust": "toz",
    "description": "tanım / açıklama",
    "accident": "kaza",
    "addressing": "hitap eden / değinen",
    "whole": "bütün / tüm",
    "report": "rapor",
    "approving": "onaylayan",
    "decisions": "kararlar",
    "council": "konsey / meclis",
    "battery": "batarya / pil",
    "action": "eylem / hareket",
    "confusion": "kafa karışıklığı",
    "court": "mahkeme",
    "demonstrating": "gösteren / kanıtlayan",
    "relativity": "görelilik / rölativite",
    "newly-discovered": "yeni keşfedilen",
    "objects": "nesneler / objeler",
    "people": "halk / insanlar",
    "constitution": "anayasa",
    "limiting": "sınırlayan",
    "sale": "satış",
    "drugs": "ilaçlar / uyuşturucular",
    "democracy": "demokrasi",
    "case": "dava / durum",
    "exhibition": "sergi",
    "some": "bazı / bazıları",
    "best": "en iyi",
    "defendant": "davalı / sanık",
    "freedom": "özgürlük",
    "promise": "vaat / söz",
    "guaranteeing": "garanti eden",
    "innovation": "yenilik / inovasyon",
    "introducing": "tanıtan / getiren",
    "methods": "yöntemler",
    "necessitating": "gerektiren",
    "careful": "dikkatli",
    "observation": "gözlem",
    "affecting": "etkileyen",
    "every": "her / her bir",
    "granting": "sağlayan / veren",
    "benefits": "faydalar",
    "old": "yaşlı / eski",
    "unemployed": "işsiz / işsizler",
    "activity": "faaliyet / aktivite",
    "endangering": "tehlikeye atan",
    "lives": "hayatlar / yaşamlar",
    "members": "üyeler",
    "governing": "yöneten / yönetici",
    "rate": "oran / hız",
    "growth": "büyüme / gelişme",
    "document": "belge / doküman",
    "authorizing": "yetki veren",
    "owner": "sahip / malik",
    "molecules": "moleküller",
    "could": "olabilirdi / -ebilirdi",
    "seen": "görülen / görülmüş",
    "police": "polis",
    "page": "sayfa",
    "there": "orada / var",
    "contains": "içerir / barındırır",
    "read": "okumak / okundu",
    "current": "akım / cereyan",
    "passes": "geçer",
    "electrode": "elektrot",
    "accused": "suçlanan / suçlandı",
    "published": "yayımlanan / yayımlandı",
    "explained": "açıklanan / açıklandı",
    "lecture": "konferans / ders",
    "passed": "geçti / kabul edildi",
    "year": "yıl / sene",
    "renaissance": "rönesans",
    "italy": "italya",
    "witness": "tanık / şahit",
    "provide": "sağlamak / sunmak",
    "electrical": "elektrik / elektriksel",
    "power": "güç / enerji",
    "proved": "kanıtlandı / ispatlandı",
    "government": "hükümet / devlet",
    "proposed": "önerilen / önerdi",
    "shape": "şekil",
    "head": "kafa / baş",
    "thorax": "göğüs / göğüs kafesi",
    "engaged": "meşgul / uğraşan",
    "plant": "bitki",
    "signature": "imza",
    "empty": "boş / boşaltmak",
    "rooms": "odalar",
    "nations": "uluslar / milletler",
    "united": "birleşmiş",
    "desire": "arzu / istek",
    "peace": "barış",
    "scientists": "bilim insanları",
    "composed": "oluşan / birleşen",
    "two": "iki",
    "simplified": "basitleştirilmiş",
    "children": "çocuklar",
    "needed": "gerekli / ihtiyaç duyulan",
    "industries": "sanayiler / endüstriler",
    "lead": "kurşun / yönlendirmek",
    "exposed": "maruz kalmış / maruz kalan",
    "air": "hava",
    "organisms": "organizmalar",
    "classified": "sınıflandırılmış / sınıflandırılan",
    "vegetable": "bitkisel / sebze",
    "kingdom": "alem / krallık",
    "energy": "enerji",
    "produced": "üretilen / üretildi",
    "atomic": "atomik",
    "pile": "reaktör / yığın",
    "atom": "atom",
    "costs": "maliyetler",
    "more": "daha fazla",
    "than": "-den daha",
    "coal": "kömür",
    "petroleum": "petrol",
    "gamma": "gama",
    "rays": "ışınlar",
    "emitted": "yayılan / salınan",
    "small": "küçük",
    "piece": "parça",
    "cobalt": "kobalt",
    "protecting": "koruyan",
    "penetrate": "nüfuz etmek / girmek",
    "cells": "hücreler",
    "woods": "ormanlar",
    "inhabited": "yaşayan / yerleşilmiş",
    "wild": "vahşi",
    "animals": "hayvanlar",
    "food": "besin / gıda",
    "enzyme": "enzim",
    "danger": "tehlike",
    "floods": "seller",
    "information": "bilgi / danışma",
    "develop": "geliştirmek",
    "programme": "program",
    "subject": "konu / ders",
    "matter": "madde / husus",
    "used": "kullanılan / kullanılmış",
    "teaching": "öğretim",
    "sent": "gönderilen / gönderildi",
    "artificial": "yapay",
    "satellites": "uydular",
    "rockets": "roketler",
    "towns": "kasabalar / kentler",
    "surrounded": "çevrili / çevrelenmiş",
    "strong": "güçlü",
    "walls": "surlar / duvarlar",
    "vibrations": "titreşimler",
    "generated": "üretilen / oluşturulan",
    "light": "ışık",
    "effects": "etkiler",
    "expected": "beklenen",
    "outlined": "taslağı çizilen / belirtilen",
    "reports": "raporlar",
    "surveys": "araştırmalar / anketler",
    "made": "yapılan / yapıldı",
    "before": "önce",
    "flood": "sel",
    "control": "kontrol",
    "act": "yasa / kanun / eylem",
    "representatives": "temsilciler",
    "book": "kitap",
    "understand": "anlamak",
    "european": "avrupalı / avrupa",
    "countries": "ülkeler",
    "heavy": "ağır / yoğun",
    "rain": "yağmur",
    "becomes": "olur / haline gelir",
    "covered": "kaplı / kaplanmış",
    "black": "siyah / kara",
    "film": "tabaka / film",
    "bacteria": "bakteriler",
    "microscopic": "mikroskobik",
    "cheap": "ucuz",
    "costs": "maliyetleri",
    "fungi": "mantarlar",
    "absorbs": "emer / soğurur",
    "large": "geniş / büyük",
    "areas": "alanlar / bölgeler",
    "provides": "sağlar / sunar",
    "educational": "eğitimsel / eğitim",
    "electro-magnetic": "elektromanyetik",
    "recorded": "kaydedilen / kaydedildi",
    "telescope": "teleskop",
    "telescopes": "teleskoplar",
    "receive": "alır / almak",
    "signals": "sinyaller",
    "primitive": "ilkel",
    "villages": "köyler",
    "gradually": "kademeli olarak / yavaş yavaş",
    "developed": "gelişen / gelişti",
    "consists": "oluşur",
    "beneficial": "faydalı / yararlı",
    "described": "tanımlanan / açıklandı"
}

print("\nCandidate wordDictionary entries for missing words:")
for m in missing:
    tr = common_tr.get(m, m)
    print(f'  "{m}": "{tr}",')
