import json

# Setup the dictionary of all modules' sentences
modules = {}

# MODULE 1
modules[1] = {
    "keyword_type": "verb",
    "data": [
        ("severe data formatting issues give rise to validation anomalies",
         "Severe data formatting issues give rise to validation anomalies.",
         "Severe data formatting issues give rise to validation anomalies, forcing international software engineering teams to inspect raw binary code strings thoroughly.",
         "ciddi veri formatlama sorunları doğrulama anomalilerine yol açar",
         "Ciddi veri formatlama sorunları doğrulama anomalilerine yol açar.",
         "Ciddi veri formatlama sorunları doğrulama anomalilerine yol açarak uluslararası yazılım mühendisliği ekiplerini ham ikili kod dizilerini derinlemesine incelemeye zorlar.",
         "give rise to", ["give rise to", "results from", "stems from", "inhibits"]),
        ("inconsistent datasets result in comprehensive compilation errors",
         "Inconsistent datasets result in comprehensive compilation errors.",
         "Inconsistent datasets result in comprehensive compilation errors because the local database schema lacks adaptive multi-layer configurations.",
         "tutarsız veri kümeleri kapsamlı derleme hatalarıyla sonuçlanır",
         "Tutarsız veri kümeleri kapsamlı derleme hatalarıyla sonuçlanır.",
         "Tutarsız veri kümeleri, yerel veritabanı şeması uyarlanabilir çok katmanlı yapılandırmalardan yoksun olduğu için kapsamlı derleme hatalarıyla sonuçlanır.",
         "result in", ["result in", "results from", "stems from", "stabilizes"]),
        ("dynamic parameter shifts are responsible for baseline calculation overrides",
         "Dynamic parameter shifts are responsible for baseline calculation overrides.",
         "Dynamic parameter shifts are responsible for baseline calculation overrides since central server nodes experience high-volume synchronization traffic.",
         "dinamik parametre kaymaları temel hesaplama geçersiz kılmalarından sorumludur",
         "Dinamik parametre kaymaları temel hesaplama geçersiz kılmalarından sorumludur.",
         "Merkez sunucu düğümleri yüksek hacimli senkronizasyon trafiği yaşadığından, temel hesaplama geçersiz kılmalarından dinamik parametre kaymaları sorumludur.",
         "are responsible for", ["are responsible for", "stems from", "contribute to", "results in"]),
        ("unauthorized external entries produce immediate firewall warnings",
         "Unauthorized external entries produce immediate firewall warnings.",
         "Unauthorized external entries produce immediate firewall warnings, which triggers an automated security script to isolate corrupted connection profiles.",
         "yetkisiz harici girişler anında güvenlik duvarı uyarıları üretir",
         "Yetkisiz harici girişler anında güvenlik duvarı uyarıları üretir.",
         "Yetkisiz harici girişler, bozulmuş bağlantı profillerini izole etmek için otomatik bir güvenlik komut dosyasını tetikleyen anında güvenlik duvarı uyarıları üretir.",
         "produce", ["produce", "produces", "producing", "produced"]),
        ("arbitrary compliance criteria cause significant implementation delays",
         "Arbitrary compliance criteria cause significant implementation delays.",
         "Arbitrary compliance criteria cause significant implementation delays although cross-disciplinary development groups work intensely to meet trade guidelines.",
         "keyfi uyumluluk kriterleri önemli uygulama gecikmelerine neden olur",
         "Keyfi uyumluluk kriterleri önemli uygulama gecikmelerine neden olur.",
         "Disiplinler arası geliştirme grupları ticari yönergeleri karşılamak için yoğun bir şekilde çalışsa da, keyfi uyumluluk kriterleri önemli uygulama gecikmelerine neden olur.",
         "cause", ["cause", "causes", "causing", "caused"]),
        ("unexpected memory leaks lead to permanent system latency",
         "Unexpected memory leaks lead to permanent system latency.",
         "Unexpected background memory leaks lead to permanent system latency, degrading active user performance indicators during long platform sessions.",
         "beklenmedik bellek sızıntıları kalıcı sistem gecikmesine yol açar",
         "Beklenmedik bellek sızıntıları kalıcı sistem gecikmesine yol açar.",
         "Beklenmedik arka plan bellek sızıntıları, uzun platform oturumları sırasında aktif kullanıcı performans göstergelerini düşürerek kalıcı sistem gecikmesine yol açar.",
         "lead to", ["lead to", "leads to", "leading to", "led to"]),
        ("unconstitutional state laws give rise to public institutional collapse",
         "Unconstitutional state laws give rise to public institutional collapse.",
         "Unconstitutional state laws give rise to public institutional collapse, forcing regional municipalities to request immediate statutory amendments.",
         "anayasa dışı devlet yasaları kamu kurumu çöküşüne yol açar",
         "Anayasa dışı devlet yasaları kamu kurumu çöküşüne yol açar.",
         "Anayasaya aykırı eyalet yasaları kamu kurumu çöküşüne yol açarak bölgesel belediyeleri derhal yasal değişiklikler talep etmeye zorlar.",
         "give rise to", ["give rise to", "stems from", "results from", "alters"]),
        ("faulty legislative draft clauses are responsible for the assembly suspension",
         "Faulty legislative draft clauses are responsible for the assembly suspension.",
         "Faulty legislative draft clauses are responsible for the assembly suspension until the constitutional committee finalizes the policy codes.",
         "kusurlu yasama taslağı maddeleri meclis askıya alınmasından sorumludur",
         "Kusurlu yasama taslağı maddeleri meclis askıya alınmasından sorumludur.",
         "Anayasa komisyonu politika kurallarını nihai hale getirene kadar, meclis askıya alınmasından kusurlu yasama taslağı maddeleri sorumludur.",
         "are responsible for", ["are responsible for", "contributes to", "causes", "results in"]),
        ("a complete lack of infrastructure causes economic stagnation",
         "A complete lack of infrastructure causes economic stagnation.",
         "A complete lack of regional infrastructure devices causes economic stagnation, reducing overall corporate investment metrics across the province.",
         "altyapı eksikliği ekonomik durgunluğa neden olur",
         "Altyapı eksikliği ekonomik durgunluğa neden olur.",
         "Bölgesel altyapı cihazlarının tamamen eksikliği ekonomik durgunluğa neden olarak eyalet genelindeki toplam kurumsal yatırım metriklerini düşürür.",
         "causes", ["causes", "cause", "causing", "caused"]),
        ("unoptimized application builds result in negative platform ratings",
         "Unoptimized application builds result in negative platform ratings.",
         "Unoptimized mobile application builds are doomed to face negative user reviews since clients encounter constant navigation lag thresholds.",
         "optimize edilmemiş uygulama derlemeleri olumsuz platform derecelendirmeleriyle sonuçlanır",
         "Optimize edilmemiş uygulama derlemeleri olumsuz platform derecelendirmeleriyle sonuçlanır.",
         "Müşteriler sürekli navigasyon gecikme eşikleriyle karşılaştığından, optimize edilmemiş mobil uygulama derlemeleri olumsuz kullanıcı yorumlarıyla karşılaşmaya mahkumdur.",
         "result in", ["result in", "stems from", "results from", "alters"]),
        ("unstable chemical mixtures produce explosive exothermic chain reactions",
         "Unstable chemical mixtures produce explosive exothermic chain reactions.",
         "Unstable chemical mixtures produce explosive exothermic chain reactions the moment technicians expose the unsealed container to sunlight.",
         "kararsız kimyasal karışımlar patlayıcı ekzotermik zincirleme reaksiyonlar üretir",
         "Kararsız kimyasal karışımlar patlayıcı ekzotermik zincirleme reaksiyonlar üretir.",
         "Teknisyenler mühürlenmemiş kabı güneş ışığına maruz bıraktığı an, kararsız kimyasal karışımlar patlayıcı ekzotermik zincirleme reaksiyonlar üretir.",
         "produce", ["produce", "produces", "producing", "produced"]),
        ("high mechanical piston friction leads to permanent engine decay",
         "High mechanical piston friction leads to permanent engine decay.",
         "High mechanical piston friction inevitably leads to permanent engine core decay under high-pressure simulation workloads.",
         "yüksek mekanik piston sürtünmesi kalıcı motor aşınmasına yol açar",
         "Yüksek mekanik piston sürtünmesi kalıcı motor aşınmasına yol açar.",
         "Yüksek mekanik piston sürtünmesi, yüksek basınçlı simülasyon iş yükleri altında kaçınılmaz olarak kalıcı motor çekirdeği aşınmasına yol açar.",
         "leads to", ["leads to", "lead to", "leading to", "led to"]),
        ("cryptographic validation failures cause transient profile lockouts",
         "Cryptographic validation failures cause transient profile lockouts.",
         "Cryptographic validation failures cause transient profile lockouts in order that sensitive server partitions can maintain data safety parameters.",
         "kriptografik doğrulama hataları geçici profil kilitlenmelerine neden olur",
         "Kriptografik doğrulama hataları geçici profil kilitlenmelerine neden olur.",
         "Hassas sunucu bölümlerinin veri güvenliği parametrelerini koruyabilmesi için, kriptografik doğrulama hataları geçici profil kilitlenmelerine neden olur.",
         "cause", ["cause", "causes", "causing", "caused"]),
        ("loose query loops produce severe execution bottlenecks",
         "Loose query loops produce severe execution bottlenecks.",
         "Loose query loops produce severe execution bottlenecks.",
         "gevşek sorgu döngüleri ciddi yürütme darboğazları üretir",
         "Gevşek sorgu döngüleri ciddi yürütme darboğazları üretir.",
         "Gevşek sorgu döngüleri ciddi yürütme darboğazları üretir.",
         "produce", ["produce", "produces", "producing", "produced"]),
        ("unmonitored server fluctuations are responsible for data degradation",
         "Unmonitored server fluctuations are responsible for data degradation.",
         "Unmonitored server fluctuations are responsible for data degradation.",
         "izlenmeyen sunucu dalgalanmaları veri bozulmasından sorumludur",
         "Izlenmeyen sunucu dalgalanmaları veri bozulmasından sorumludur.",
         "Izlenmeyen sunucu dalgalanmaları veri bozulmasından sorumludur.",
         "are responsible for", ["are responsible for", "contributes to", "causes", "results in"]),
        ("flexible parameter fields contribute to significant implementation delays",
         "Flexible parameter fields contribute to significant implementation delays.",
         "Flexible parameter fields contribute to significant implementation delays although cross-disciplinary groups work intensely to meet guidelines.",
         "esnek parametre alanları önemli uygulama gecikmelerine katkıda bulunur",
         "Esnek parametre alanları önemli uygulama gecikmelerine katkıda bulunur.",
         "Disiplinler arası gruplar yönergeleri karşılamak için yoğun bir şekilde çalışsa da, esnek parametre alanları önemli uygulama gecikmelerine katkıda bulunur.",
         "contribute to", ["contribute to", "contributes to", "contributing to", "contributed to"]),
        ("loose database integration has resulted in severe compilation errors",
         "Loose database integration has resulted in severe compilation errors.",
         "Loose database integration has resulted in severe compilation errors because the regional schema lacks adaptive multi-layer configurations.",
         "gevşek veritabanı entegrasyonu ciddi derleme hatalarıyla sonuçlanmıştır",
         "Gevşek veritabanı entegrasyonu ciddi derleme hatalarıyla sonuçlanmıştır.",
         "Bölgesel şema uyarlanabilir çok katmanlı yapılandırmalardan yoksun olduğu için, gevşek veritabanı entegrasyonu ciddi derleme hatalarıyla sonuçlanmıştır.",
         "has resulted in", ["has resulted in", "have resulted in", "result in", "results from"]),
        ("sudden technical overrides trigger baseline calculation overrides",
         "Sudden technical overrides trigger baseline calculation overrides.",
         "Sudden technical overrides trigger baseline calculation overrides when central server nodes experience unexpected high-volume data traffic.",
         "ani teknik geçersiz kılmalar temel hesaplama geçersiz kılmalarını tetikler",
         "Ani teknik geçersiz kılmalar temel hesaplama geçersiz kılmalarını tetikler.",
         "Merkez sunucu düğümleri beklenmedik yüksek hacimli veri trafiği yaşadığında, ani teknik geçersiz kılmalar temel hesaplama geçersiz kılmalarını tetikler.",
         "trigger", ["trigger", "triggers", "triggering", "triggered"]),
        ("unauthorized external entries bring about immediate firewall warnings",
         "Unauthorized external entries bring about immediate firewall warnings.",
         "Unauthorized external entries bring about immediate firewall warnings, forcing the automated security package to isolate corrupted profiles.",
         "yetkisiz harici girişler anında güvenlik duvarı uyarılarına yol açar",
         "Yetkisiz harici girişler anında güvenlik duvarı uyarılarına yol açar.",
         "Yetkisiz harici girişler, otomatik güvenlik paketini bozulmuş profilleri izole etmeye zorlayarak anında güvenlik duvarı uyarılarına yol açar.",
         "bring about", ["bring about", "brings about", "bringing about", "brought about"]),
        ("unverified cryptographic tokens are one of the causes of validation anomalies",
         "Unverified cryptographic tokens are one of the causes of validation anomalies.",
         "Inconsistent technical datasets are one of the causes of validation anomalies, forcing software engineering teams to analyze binary code strings.",
         "doğrulanmamış kriptografik belirteçler doğrulama anomalilerinin nedenlerinden biridir",
         "Doğrulanmamış kriptografik belirteçler doğrulama anomalilerinin nedenlerinden biridir.",
         "Tutarsız teknik veri kümeleri, yazılım mühendisliği ekiplerini ikili kod dizilerini analiz etmeye zorlayarak doğrulama anomalilerinin nedenlerinden biridir.",
         "are one of the causes of", ["are one of the causes of", "causes of", "causes", "stems from"])
    ]
}

# MODULE 2: Semicolon + Transition Adverb
m2_keywords = ["therefore", "consequently", "as a result", "hence", "thus", "so", "accordingly"]
m2_distractors = ["however", "although", "whereas", "despite"]
modules[2] = {
    "keyword_type": "adverb",
    "data": [
        ("therefore", "Vitamins were lacking; therefore, health was poor.",
         "Vitamins were lacking inside the urban center; therefore, public health indicators remained exceptionally poor last quarter.",
         "bu nedenle", "Vitaminler eksikti; bu nedenle sağlık zayıftı.",
         "Kent merkezinde vitaminler eksikti; bu nedenle halk sağlığı göstergeleri geçen çeyrekte son derece zayıf kaldı.",
         "therefore", ["therefore", "however", "although", "despite"]),
        ("consequently", "Data formatting issues occurred; consequently, validation anomalies arose.",
         "Serious data formatting issues occurred during migration; consequently, severe validation anomalies arose within the central schema layers.",
         "sonuç olarak", "Veri formatlama sorunları meydana geldi; sonuç olarak doğrulama anomalileri ortaya çıktı.",
         "Geçiş sırasında ciddi veri formatlama sorunları meydana geldi; sonuç olarak merkezi şema katmanlarında ciddi doğrulama anomalileri ortaya çıktı.",
         "consequently", ["consequently", "nonetheless", "whereas", "but"]),
        ("as a result", "Datasets were inconsistent; and as a result, compilation errors developed.",
         "Underlying datasets were completely inconsistent; and as a result, comprehensive compilation errors developed before technicians isolated the drive.",
         "sonuç olarak", "Veri kümeleri tutarsızdı ve sonuç olarak derleme hataları gelişti.",
         "Temel veri kümeleri tamamen tutarsızdı ve sonuç olarak teknisyenler sürücüyü izole etmeden önce kapsamlı derleme hataları gelişti.",
         "as a result", ["as a result", "on the contrary", "although", "since"]),
        ("with the result that", "Parameter fields shifted; with the result that calculation overrides triggered.",
         "Core parameter fields shifted during stress diagnostic loops; with the result that calculation overrides triggered across production nodes.",
         "bunun sonucunda", "Parametre alanları kaydı; bunun sonucunda hesaplama geçersiz kılmaları tetiklendi.",
         "Stres teşhis döngüleri sırasında temel parametre alanları kaydı; bunun sonucunda üretim düğümlerinde hesaplama geçersiz kılmaları tetiklendi.",
         "with the result that", ["with the result that", "even if", "in spite of", "whereas"]),
        ("as a consequence", "External entries were unauthorized; and as a consequence, firewalls locked.",
         "External client profiles were unauthenticated and unauthorized; and as a consequence, automated firewalls locked down the primary gateway.",
         "bunun bir sonucu olarak", "Harici girişler yetkisizdi ve bunun bir sonucu olarak güvenlik duvarları kilitlendi.",
         "Harici istemci profilleri kimlik doğrulaması yapılmamış ve yetkisizdi; bunun bir sonucu olarak otomatik güvenlik duvarları birincil geçidi kilitledi.",
         "as a consequence", ["as a consequence", "nonetheless", "even though", "likewise"]),
        ("for this reason", "Compliance criteria were arbitrary; for this reason, implementation delayed.",
         "Compliance criteria were highly arbitrary; for this reason, software implementation delayed despite developers utilizing advanced artificial intelligence tools.",
         "bu nedenle", "Uyumluluk kriterleri keyfiydi; bu nedenle uygulama gecikti.",
         "Uyumluluk kriterleri son derece keyfiydi; bu nedenle geliştiriciler gelişmiş yapay zeka araçları kullanmalarına rağmen yazılım uygulaması gecikti.",
         "for this reason", ["for this reason", "in contrast", "although", "inasmuch as"]),
        ("consequently", "Memory leaks occurred unexpectedly; consequently, system latency increased.",
         "Background memory leaks occurred unexpectedly over the weekend; consequently, system latency increased, degrading the gamified learning interface runtime.",
         "sonuç olarak", "Bellek sızıntıları beklenmedik bir şekilde meydana geldi; sonuç olarak sistem gecikmesi arttı.",
         "Hafta sonu beklenmedik bir şekilde arka plan bellek sızıntıları meydana geldi; sonuç olarak sistem gecikmesi artarak oyunlaştırılmış öğrenme arayüzü çalışma süresini düşürdü.",
         "consequently", ["consequently", "but", "although", "unless"]),
        ("as a result", "State laws were unconstitutional; and as a result, institutions collapsed.",
         "Regional state laws were unconstitutional; and as a result, local public institutions collapsed once the ministry enforced statutory checks.",
         "sonuç olarak", "Eyalet yasaları anayasaya aykırıydı ve sonuç olarak kurumlar çöktü.",
         "Bölgesel eyalet yasaları anayasaya aykırıydı ve sonuç olarak bakanlık yasal kontrolleri uyguladığında yerel kamu kurumları çöktü.",
         "as a result", ["as a result", "even though", "otherwise", "besides"]),
        ("with the result that", "Draft clauses were faulty; with the result that the assembly suspended.",
         "Legislative draft clauses were significantly faulty; with the result that the assembly suspended further voting rounds until next month.",
         "bunun sonucunda", "Taslak maddeler kusurluydu; bunun sonucunda meclis askıya alındı.",
         "Yasama taslağı maddeleri önemli ölçüde kusurluydu; bunun sonucunda meclis gelecek aya kadar sonraki oylama turlarını askıya aldı.",
         "with the result that", ["with the result that", "provided that", "whereas", "nonetheless"]),
        ("therefore", "Regional infrastructure was lacking; therefore, the economy stagnated.",
         "Vital infrastructure components were completely lacking; therefore, the regional commercial economy stagnated despite initial corporate investment packages.",
         "bu nedenle", "Bölgesel altyapı eksikti; bu nedenle ekonomi durgunlaştı.",
         "Hayati altyapı bileşenleri tamamen eksikti; bu nedenle ilk kurumsal yatırım paketlerine rağmen bölgesel ticari ekonomi durgunlaştı.",
         "therefore", ["therefore", "however", "though", "whereas"]),
        ("consequently", "Application builds were unoptimized; consequently, user ratings dropped.",
         "Mobile application builds were unoptimized; consequently, active user ratings dropped significantly ahead of the global marketing campaign.",
         "sonuç olarak", "Uygulama derlemeleri optimize edilmemişti; sonuç olarak kullanıcı puanları düştü.",
         "Mobil uygulama derlemeleri optimize edilmemişti; sonuç olarak küresel pazarlama kampanyası öncesinde aktif kullanıcı puanları önemli ölçüde düştü.",
         "consequently", ["consequently", "nevertheless", "in order that", "since"]),
        ("as a result", "Chemical mixtures were unstable; and as a result, reactions triggered.",
         "Organic chemical mixtures were highly unstable; and as a result, explosive exothermic reactions triggered inside the laboratory vacuum chamber.",
         "sonuç olarak", "Kimyasal karışımlar kararsızdı ve sonuç olarak reaksiyonlar tetiklendi.",
         "Organik kimyasal karışımlar son derece kararsızdı ve sonuç olarak laboratuvar vakum odasında patlayıcı ekzotermik reaksiyonlar tetiklendi.",
         "as a result", ["as a result", "in spite of", "although", "whereas"]),
        ("as a consequence", "Piston friction was high; and as a consequence, the engine decayed.",
         "Mechanical piston friction values were exceptionally high; and as a consequence, the main engine core decayed under high-pressure testing.",
         "bunun bir sonucu olarak", "Piston sürtünmesi yüksekti ve bunun bir sonucu olarak motor aşındı.",
         "Mekanik piston sürtünme değerleri son derece yüksekti ve bunun bir sonucu olarak ana motor çekirdeği yüksek basınçlı testler altında aşındı.",
         "as a consequence", ["as a consequence", "instead of", "provided", "likewise"]),
        ("for this reason", "Validation tokens failed; for this reason, profile logouts occurred.",
         "Cryptographic validation tokens failed the authentication loop; for this reason, transient profile logouts occurred to secure client identity logs.",
         "bu nedenle", "Doğrulama belirteçleri başarısız oldu; bu nedenle profil çıkışları gerçekleşti.",
         "Kriptografik doğrulama belirteçleri kimlik doğrulama döngüsünde başarısız oldu; bu nedenle istemci kimliği günlüklerini güvence altına almak için geçici profil çıkışları gerçekleşti.",
         "for this reason", ["for this reason", "though", "on the contrary", "inasmuch as"]),
        ("consequently", "Query loops were loose; consequently, execution bottlenecks formed.",
         "Database query loops were loose and unhandled; consequently, catastrophic execution bottlenecks formed while handling high-volume transaction traffic.",
         "sonuç olarak", "Sorgu döngüleri gevşekti; sonuç olarak yürütme darboğazları oluştu.",
         "Veritabanı sorgu döngüleri gevşek ve işlenmemişti; sonuç olarak yüksek hacimli işlem trafiği yönetilirken yıkıcı yürütme darboğazları oluştu.",
         "consequently", ["consequently", "otherwise", "whereas", "although"]),
        ("thus", "Vitamins were lacking; thus, health was poor.",
         "Vitamins were lacking inside the central urban zone; thus, public health indicators remained exceptionally poor throughout the year.",
         "böylece", "Vitaminler eksikti; böylece sağlık zayıftı.",
         "Merkezi kent bölgesinde vitaminler eksikti; böylece halk sağlığı göstergeleri yıl boyunca son derece zayıf kaldı.",
         "thus", ["thus", "however", "although", "despite"]),
        ("so", "Data formatting issues occurred, so validation anomalies arose.",
         "Serious data formatting issues occurred inside the primary database partition, so severe validation anomalies arose within the central schema layers.",
         "bu yüzden", "Veri formatlama sorunları meydana geldi, bu yüzden doğrulama anomalileri ortaya çıktı.",
         "Birincil veritabanı bölümünde ciddi veri formatlama sorunları meydana geldi, bu yüzden merkezi şema katmanlarında ciddi doğrulama anomalileri ortaya çıktı.",
         "so", ["so", "yet", "although", "but"]),
        ("as an immediate result", "Datasets were inconsistent; as an immediate result, compilation errors developed.",
         "Underlying datasets were completely inconsistent within the main directory; as an immediate result, comprehensive compilation errors developed rapidly.",
         "ani bir sonuç olarak", "Veri kümeleri tutarsızdı; ani bir sonuç olarak derleme hataları gelişti.",
         "Ana dizin içindeki temel veri kümeleri tamamen tutarsızdı; ani bir sonuç olarak kapsamlı derleme hataları hızla gelişti.",
         "as an immediate result", ["as an immediate result", "contrarily", "although", "while"]),
        ("on that account", "Parameter fields shifted; on that account, calculation overrides triggered.",
         "Core parameter fields shifted during stress diagnostic loops over the weekend; on that account, calculation overrides triggered across production nodes.",
         "bu nedenle", "Parametre alanları kaydı; bu nedenle hesaplama geçersiz kılmaları tetiklendi.",
         "Hafta sonu stres teşhis döngüleri sırasında temel parametre alanları kaydı; bu nedenle üretim düğümlerinde hesaplama geçersiz kılmaları tetiklendi.",
         "on that account", ["on that account", "even if", "in spite of", "whereas"]),
        ("accordingly", "Compliance criteria were arbitrary; accordingly, implementation delayed.",
         "Compliance criteria were highly arbitrary across specific sectors; accordingly, software implementation delayed despite developers utilizing advanced digital platforms.",
         "buna göre", "Uyumluluk kriterleri keyfiydi; buna göre uygulama gecikti.",
         "Belirli sektörlerde uyumluluk kriterleri son derece keyfiydi; buna göre geliştiriciler gelişmiş dijital platformlar kullanmalarına rağmen yazılım uygulaması gecikti.",
         "accordingly", ["accordingly", "nonetheless", "even though", "otherwise"])
    ]
}

print(f"Modules 1 and 2 defined.")
